spring:
  thymeleaf:
    cache: false

  application:
    name: DLP-system

  datasource:
    url: jdbc:mysql://localhost:3306/dlp_system
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.security: DEBUG

